name: Create Release on Version Change
on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: package.json에서 현재 버전 가져오기
        id: get_version
        run: echo "version=$(node -e 'console.log(require("./package.json").version)')" >> $GITHUB_OUTPUT

      - name: 이전 릴리즈 버전 가져오기
        id: get_previous_version
        run: echo "previous_version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: 버전 비교
        id: version_comparison
        run: echo "version_changed=${{ steps.get_version.outputs.version != steps.get_previous_version.outputs.previous_version }}" >> $GITHUB_OUTPUT

      - name: 릴리즈 생성
        if: steps.version_comparison.outputs.version_changed == 'true'
        run: |
          RELEASE_TITLE="v${{ steps.get_version.outputs.version }}"
          RELEASE_BODY=$(git log --pretty=format:"- %s%n" ${{ steps.get_previous_version.outputs.previous_version }}..HEAD)
          echo "Creating release $RELEASE_TITLE"
          echo "Title: $RELEASE_TITLE"
          echo "Body: $RELEASE_BODY"
          gh release create $RELEASE_TITLE -t "$RELEASE_TITLE" -n "$RELEASE_BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_PACKAGE }}
